//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Domain.Entities
{
    public partial class Competition
    {
        public Competition()
        {
            this.Problems = new HashSet<Problem>();
            this.TeamInCompetitions = new HashSet<TeamInCompetition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AdminId { get; set; }
        public string EntryPassword { get; set; }
    
        public virtual ICollection<Problem> Problems { get; set; }
        public virtual ICollection<TeamInCompetition> TeamInCompetitions { get; set; }
        public virtual Setting Setting { get; set; }
    }
    
}
