//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Domain.Entities
{
    public partial class Problem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string ExampleInput { get; set; }
        public string ExampleOutput { get; set; }
        public string ExpectedOutput { get; set; }
        public int CompetitionId { get; set; }
        public string ActualInput { get; set; }
    
        public virtual Competition Competition { get; set; }
    }
    
}
