//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Domain.Entities
{
    public partial class Solution
    {
        public int Id { get; set; }
        public System.DateTime SubmissionTime { get; set; }
        public string Result { get; set; }
        public Nullable<int> Score { get; set; }
        public int TeamId { get; set; }
        public System.DateTime JudgeTime { get; set; }
        public string ResultDescription { get; set; }
        public int ProblemId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual File SourceFile { get; set; }
    }
    
}
