//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CC.Domain.Entities
{
    public partial class Team
    {
        public Team()
        {
            this.People = new HashSet<Person>();
            this.TeamInCompetitions = new HashSet<TeamInCompetition>();
            this.Solutions = new HashSet<Solution>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<TeamInCompetition> TeamInCompetitions { get; set; }
        public virtual ICollection<Solution> Solutions { get; set; }
    }
    
}
